In [132]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from numpy.linalg import det,inv 

data = pd.read_csv('Class1.csv')

# data1 = data.loc[data['Risk']==1]
# data2 = data.loc[data['Risk']==0]
# data1 = data1.drop(['Risk'],axis=1)
# data2 = data2.drop(['Risk'],axis=1)

In [94]:
print(np.shape(data))

(1266, 4)


In [110]:
np.exp(-10)

4.5399929762484854e-05

In [133]:
d1_len = len(data)
h = 4
b=5
m = np.zeros(b*h).reshape(b,h)
C = np.zeros(b*h*h).reshape(b,h,h)
w = np.ones(b)/b

for i in range(b):
    C[i] = np.eye(h,h)

    
def Gau(x,m,C):
    #print(np.dot(np.dot((x-m).T,inv(C)),(x-m))-12.5*np.log(1/(2*np.pi))-0.5*np.log(det(C)))
    lnprob = -0.5*np.dot(np.dot((x-m).T,inv(C)),(x-m))-2*np.log(1/(2*np.pi))-0.5*np.log(det(C))
    if(lnprob>-10):
        return np.exp(lnprob)
    else:
        return 0.0000001

def denom_sum(n,x,m,C,w):
    s=0
    for i in range(n):
        s=s+w[i]*Gau(x,m[i],C[i])
    return s

for i in range(b):
    ind = np.random.randint(0,len(data))
    m[i]=data.iloc[ind]

In [134]:
m

array([[  5.75341788,   5.68269705,   4.89030915,   6.15195312],
       [-16.23856658,  -6.10660657, -10.92223958,  -4.4560106 ],
       [  8.61766269,   6.34093402,   6.53368463,   8.25735516],
       [ -1.39659905,  -3.88073277,  -5.75109153,  -0.46834317],
       [ -5.39647392,  -8.66026159, -10.89790878,  -8.64351835]])

In [135]:
p = np.zeros(b*d1_len).reshape(b,d1_len)
for k in range(20):
    for j in range(b):
        for i in range(d1_len):
            x = data.iloc[i].to_numpy()
            #print(denom_sum(3,x,m,C,w))
            p[j][i] = w[j]*Gau(x,m[j],C[j])/denom_sum(b,x,m,C,w)
        X = data.iloc[:].to_numpy()
#         print(np.shape(X))
#         print(np.shape(p))
        m[j]=np.dot(p[j].reshape(1,np.shape(p[j])[0]),X)/np.sum(p[j])
        w[j]=np.sum(p[j])/d1_len
        m_tmp = X-np.dot(np.ones((d1_len,1)),m[j].reshape(1,np.shape(m[[j]])[1]))
        Ctmp = np.zeros(b*h*h).reshape(b,h,h)
        Ctmp[j]=np.dot((m_tmp.T*(p[j].reshape(1,np.shape(p[j])[0]))),m_tmp)/np.sum(p[j])
        for l in range(h):
            C[j,l,l] = Ctmp[j,l,l]

In [137]:
m

array([[ -0.15826965,   2.33533576,   1.25389705,   1.39767006],
       [  3.37630483,   0.58568413,   9.70341597,   3.46700548],
       [  5.66585376,   5.58209431,   5.55897643,   5.23750524],
       [ -4.65123748,  -5.0017821 ,  -4.85661016,  -4.84251857],
       [  5.17317859,   0.47040025, -11.15371014,   3.27732916]])

In [91]:
import numpy as np
from sklearn import mixture
np.random.seed(1)
g = mixture.GaussianMixture(n_components=5)
# Generate random observations with two modes centered on 0
# and 10 to use for training.
obs = data
g.fit(obs) 

np.round(g.weights_, 3)

np.round(g.means_, 2)

# np.round(g.covars_, 2) 

array([[ 6.32,  6.35,  6.4 ,  6.22],
       [-4.94, -5.1 , -5.08, -5.09],
       [ 1.84,  3.  ,  2.45,  2.09],
       [ 6.23, -3.61,  3.24,  0.42],
       [-1.11,  5.68,  2.37,  5.9 ]])