In [12]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from numpy.linalg import det,inv 

data = pd.read_csv('audit_risk1.csv')
data1 = data.loc[data['Risk']==1]
data2 = data.loc[data['Risk']==0]
data1 = data1.drop(['Risk'],axis=1)
data2 = data2.drop(['Risk'],axis=1)


In [13]:
print(np.shape(data2))
print(np.shape(data1))

(42, 5)
(57, 5)


In [14]:
data1.head()

Risk_A  Risk_B  Risk_C  Risk_D  RiSk_E
0   2.508   0.500     1.0   0.676     0.4
3   0.000   6.480     3.6   7.050     0.4
6   0.440   2.964     1.0  26.970     0.4
7   5.100   7.218     2.2   3.116     0.4
8   5.040   6.630     2.2   2.936     0.4

In [15]:
m = np.zeros(3*5).reshape(3,5)
C = np.zeros(3*5*5).reshape(3,5,5)
w = np.ones(3)/3

In [16]:
# for i in range(3):
#     ind = np.random.randint(0,3) 
#     m[i]=data1.iloc[ind]
for i in range(3):
    C[i] = np.eye(5,5)

def Gau(x,m,C):
    #print(np.dot(np.dot((x-m).T,inv(C)),(x-m))-12.5*np.log(1/(2*np.pi))-0.5*np.log(det(C)))
    lnprob = -0.5*np.dot(np.dot((x-m).T,inv(C)),(x-m))-2.5*np.log(1/(2*np.pi))-0.5*np.log(det(C))
    return (lnprob)

In [17]:
C

array([[[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]],

       [[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]],

       [[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]]])

In [18]:
C[0,0,0]

1.0

In [19]:
def denom_sum(n,x,m,C,w):
    s=0
    for i in range(n):
        s=s+w[i]*Gau(x,m[i],C[i])
    return s

In [20]:

p = np.zeros(3*57).reshape(3,57)
for k in range(20):
    for j in range(3):
        for i in range(57):
            x = data1.iloc[i].to_numpy()
            #print(denom_sum(3,x,m,C,w))
            p[j][i] = w[j]*Gau(x,m[j],C[j])/denom_sum(3,x,m,C,w)
        X = data1.iloc[:].to_numpy()    
        m[j]=np.dot(p[j].reshape(1,np.shape(p[j])[0]),X)/np.sum(p[j])
        w[j]=np.sum(p[j])/57.0
        m_tmp = X-np.dot(np.ones((57,1)),m[j].reshape(1,np.shape(m[[j]])[1]))
        Ctmp = np.zeros(3*5*5).reshape(3,5,5)
        Ctmp[j]=np.dot((m_tmp.T*(p[j].reshape(1,np.shape(p[j])[0]))),m_tmp)/np.sum(p[j])
        for l in range(5):
            C[j,l,l] = Ctmp[j,l,l]
    
    

In [28]:
Ctmp = np.zeros(3*5*5).reshape(3,5,5)
for i in range(3):
    for j in range(5):
        Ctmp[i,j,j] = C[i,j,j]    

In [23]:
C

array([[[3.48131239e+01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00],
        [0.00000000e+00, 1.64269243e+02, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 4.87709412e-01, 0.00000000e+00,
         0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.01970608e+04,
         0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         7.57349000e-02]],

       [[3.48480384e+01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00],
        [0.00000000e+00, 1.64280980e+02, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 4.87761971e-01, 0.00000000e+00,
         0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.02082689e+04,
         0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         7.57408808e-02]],

      

In [24]:
m = np.zeros(3*5).reshape(3,5)
C = np.zeros(3*5*5).reshape(3,5,5)
w = np.ones(3)/3

for i in range(3):
    C[i] = np.eye(5,5)

def Gau(x,m,C):
    #print(np.dot(np.dot((x-m).T,inv(C)),(x-m))-12.5*np.log(1/(2*np.pi))-0.5*np.log(det(C)))
    lnprob = -0.5*np.dot(np.dot((x-m).T,inv(C)),(x-m))-2.5*np.log(1/(2*np.pi))-0.5*np.log(det(C))
    return (lnprob)

def denom_sum(n,x,m,C,w):
    s=0
    for i in range(n):
        s=s+w[i]*Gau(x,m[i],C[i])
    return s

p = np.zeros(3*42).reshape(3,42)
for k in range(10):
    for j in range(3):
        for i in range(42):
            x = data2.iloc[i].to_numpy()
            #print(denom_sum(3,x,m,C,w))
            p[j][i] = w[j]*Gau(x,m[j],C[j])/denom_sum(3,x,m,C,w)
        X = data2.iloc[:].to_numpy()    
        m[j]=np.dot(p[j].reshape(1,np.shape(p[j])[0]),X)/np.sum(p[j])
        w[j]=np.sum(p[j])/42.0
        m_tmp = X-np.dot(np.ones((42,1)),m[j].reshape(1,np.shape(m[[j]])[1]))
        Ctmp = np.zeros(3*5*5).reshape(3,5,5)
        Ctmp[j]=np.dot((m_tmp.T*(p[j].reshape(1,np.shape(p[j])[0]))),m_tmp)/np.sum(p[j])
        for l in range(5):
            C[j,l,l] = Ctmp[j,l,l]
         

LinAlgError: Singular matrix

In [7]:
C

array([[[0.15623046, 0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.32078499, 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.38878506, 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.00725624]],

       [[1.        , 0.        , 0.        , 0.        , 0.        ],
        [0.        , 1.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 1.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 1.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 1.        ]],

       [[1.        , 0.        , 0.        , 0.        , 0.        ],
        [0.        , 1.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 1.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 1.        , 0.        ],
        [0.     

In [116]:
A = np.array([1,2,3,4,5,6,9,8,7,10])
A = A.reshape(2,5)
b = np.array([1,2,3,4,5])
K = A*b
K


array([[ 1,  4,  9, 16, 25],
       [ 6, 18, 24, 28, 50]])

In [117]:
a = data1.iloc[:].to_numpy()
b=a.reshape(25,305)
np.shape(a)[0]
p = np.zeros(3*305).reshape(3,305)
np.shape(p[1].reshape(np.shape(p[1])[0],1))
c = np.dot(np.ones((305,1)),m[1].reshape(1,np.shape(m[1])[0]))
np.shape(c)

(305, 25)

In [23]:
cor1 = data1.corr()
upper1 =cor1.where(np.triu(np.ones(cor1.shape), k=1).astype(np.bool))
to_drop1 = [column for column in upper1.columns if any(upper1[column] >=0.89)]
data1 = data1.drop(to_drop1,axis = 1)

cor2 = data2.corr()
upper2 =cor2.where(np.triu(np.ones(cor2.shape), k=1).astype(np.bool))
to_drop2 = [column for column in upper2.columns if any(upper2[column] >=0.89)]
data2 = data2.drop(to_drop2,axis = 1)

In [30]:
to_drop2

['Risk_A',
 'Risk_B',
 'Score_B.1',
 'Risk_C',
 'Risk_D',
 'RiSk_E',
 'Prob',
 'Risk_F',
 'CONTROL_RISK']

In [31]:
to_drop1

['Risk_A',
 'Risk_B',
 'TOTAL',
 'Score_B.1',
 'Risk_C',
 'Risk_D',
 'RiSk_E',
 'Risk_F']

In [ ]:
plt.figure(figsize=(15, 15))
cor = data.corr()
sns.heatmap(cor,annot = True)
cor

data.dropna()
data

corr_matrix = cor
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(np.bool))
to_drop = [column for column in upper.columns if any(upper[column] >=0.9)]
to_drop

data.drop(to_drop,axis = 1)

In [32]:
data[0:22]

Sector_score LOCATION_ID  PARA_A  Score_A  Risk_A  PARA_B  Score_B  \
0           3.89          23    4.18      0.6   2.508    2.50      0.2   
1           3.89           6    0.00      0.2   0.000    4.83      0.2   
2           3.89           6    0.51      0.2   0.102    0.23      0.2   
3           3.89           6    0.00      0.2   0.000   10.80      0.6   
4           3.89           6    0.00      0.2   0.000    0.08      0.2   
5           3.89           6    0.00      0.2   0.000    0.83      0.2   
6           3.89           7    1.10      0.4   0.440    7.41      0.4   
7           3.89           8    8.50      0.6   5.100   12.03      0.6   
8           3.89           8    8.40      0.6   5.040   11.05      0.6   
9           3.89           8    3.98      0.6   2.388    0.99      0.2   
10          3.89           8    5.43      0.6   3.258   10.77      0.6   
11          3.89           8   15.38      0.6   9.228   40.14      0.6   
12          3.89           8    5.47      0.6   3.282    7.63      0.4   
13          3.89           8    1.09      0.4   0.436    0.35      0.2   
14          3.89           8    0.00      0.2   0.000    0.84      0.2   
15          3.89          13    1.95      0.4   0.780    9.01      0.4   
16          3.89          37    8.54      0.6   5.124   31.63      0.6   
17          3.89          37    4.18      0.6   2.508    4.83      0.2   
18          3.89          37    1.81      0.4   0.724    1.03      0.2   
19          3.89          37    4.86      0.6   2.916   46.78      0.6   
20          3.89          24    6.26      0.6   3.756   14.10      0.6   
21          3.89           3    0.02      0.2   0.004    5.94      0.4   

    Risk_B  TOTAL  numbers  ...  RiSk_E  History  Prob  Risk_F  Score  \
0    0.500   6.68      5.0  ...     0.4        0   0.2     0.0    2.4   
1    0.966   4.83      5.0  ...     0.4        0   0.2     0.0    2.0   
2    0.046   0.74      5.0  ...     0.4        0   0.2     0.0    2.0   
3    6.480  10.80      6.0  ...     0.4        0   0.2     0.0    4.4   
4    0.016   0.08      5.0  ...     0.4        0   0.2     0.0    2.0   
5    0.166   0.83      5.0  ...     0.4        0   0.2     0.0    2.0   
6    2.964   8.51      5.0  ...     0.4        0   0.2     0.0    3.2   
7    7.218  20.53      5.5  ...     0.4        0   0.2     0.0    4.2   
8    6.630  19.45      5.5  ...     0.4        0   0.2     0.0    4.2   
9    0.198   4.97      5.0  ...     0.4        0   0.2     0.0    2.4   
10   6.462  16.20      5.0  ...     0.4        0   0.2     0.0    3.6   
11  24.084  55.52      5.0  ...     0.8        1   0.4     0.4    4.0   
12   3.052  13.10      5.0  ...     0.4        1   0.4     0.4    3.6   
13   0.070   1.44      5.0  ...     0.4        0   0.2     0.0    2.2   
14   0.168   0.84      5.0  ...     0.4        0   0.2     0.0    2.0   
15   3.604  10.96      5.0  ...     0.4        0   0.2     0.0    3.0   
16  18.978  40.17      5.0  ...     0.4        1   0.4     0.4    4.2   
17   0.966   9.01      5.5  ...     0.4        0   0.2     0.0    3.2   
18   0.206   2.84      5.0  ...     0.4        0   0.2     0.0    2.2   
19  28.068  51.64      5.5  ...     0.4        0   0.2     0.0    4.4   
20   8.460  20.36      5.0  ...     0.4        1   0.4     0.4    4.2   
21   2.376   5.96      5.0  ...     0.4        0   0.2     0.0    2.6   

    Inherent_Risk  CONTROL_RISK  Detection_Risk  Audit_Risk  Risk  
0          8.5740           0.4             0.5     1.71480     1  
1          2.5540           0.4             0.5     0.51080     0  
2          1.5480           0.4             0.5     0.30960     0  
3         17.5300           0.4             0.5     3.50600     1  
4          1.4160           0.4             0.5     0.28320     0  
5          2.1560           0.4             0.5     0.43120     0  
6         31.7740           0.4             0.5     6.35480     1  
7         18.0340           0.4             0.5     3.60680     1  
8        

In [44]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

data = pd.read_csv('audit_risk.csv')
data = data[['Risk_A','Risk_B','Risk_C','TOTAL','Risk_D','RiSk_E','Risk_F','Score','Inherent_Risk','CONTROL_RISK','Audit_Risk','Risk']]
data1 = data.loc[data['Risk']==1]
data2 = data.loc[data['Risk']==0]
data1 = data1.drop(['Detection_Risk','Risk'],axis=1)
data2 = data2.drop(['Detection_Risk','Risk'],axis=1)

In [45]:
data

Risk_A    Risk_B  Risk_C    TOTAL    Risk_D  RiSk_E  Risk_F  Score  \
0     2.508   0.50000     1.0   6.6800    0.6760     0.4     0.0    2.4   
1     0.000   0.96600     1.0   4.8300    0.1880     0.4     0.0    2.0   
2     0.102   0.04600     1.0   0.7400    0.0000     0.4     0.0    2.0   
3     0.000   6.48000     3.6  10.8000    7.0500     0.4     0.0    4.4   
4     0.000   0.01600     1.0   0.0800    0.0000     0.4     0.0    2.0   
5     0.000   0.16600     1.0   0.8300    0.5900     0.4     0.0    2.0   
6     0.440   2.96400     1.0   8.5100   26.9700     0.4     0.0    3.2   
7     5.100   7.21800     2.2  20.5300    3.1160     0.4     0.0    4.2   
8     5.040   6.63000     2.2  19.4500    2.9360     0.4     0.0    4.2   
9     2.388   0.19800     1.0   4.9700    0.3860     0.4     0.0    2.4   
10    3.258   6.46200     1.0  16.2000    0.8840     0.4     0.0    3.6   
11    9.228  24.08400     1.0  55.5200    0.1920     0.8     0.4    4.0   
12    3.282   3.05200     1.0  13.1000    6.2580     0.4     0.4    3.6   
13    0.436   0.07000     1.0   1.4400    0.0000     0.4     0.0    2.2   
14    0.000   0.16800     1.0   0.8400    0.0014     0.4     0.0    2.0   
15    0.780   3.60400     1.0  10.9600    3.6000     0.4     0.0    3.0   
16    5.124  18.97800     1.0  40.1700   24.7680     0.4     0.4    4.2   
17    2.508   0.96600     2.2   9.0100    8.4180     0.4     0.0    3.2   
18    0.724   0.20600     1.0   2.8400    0.0000     0.4     0.0    2.2   
19    2.916  28.06800     2.2  51.6400   37.9080     0.4     0.0    4.4   
20    3.756   8.46000     1.0  20.3600   20.5440     0.4     0.4    4.2   
21    0.004   2.37600     1.0   5.9600    0.0020     0.4     0.0    2.6   
22    3.186  13.67400     1.0  28.1000  123.1140     0.4     0.4    4.2   
23    0.188   0.00200     1.0   0.9500    0.0200     0.4     0.0    2.0   
24    3.468  34.75200     1.0  63.7000    6.6960     0.4     0.0    4.0   
25    4.452   0.44800     1.0   9.6600    0.2500     0.4     0.0    2.4   
26    0.000   0.22000     1.0   1.1000    0.0014     0.4     0.0    2.0   
27    4.110  19.05600     1.0  38.6100    0.2920     0.4     0.0    3.6   
28    0.000   0.20600     1.0   1.0300    0.0000     0.4     0.0    2.0   
29    0.000   0.15000     1.0   0.7500    2.7120     0.4     0.0    2.2   
..      ...       ...     ...      ...       ...     ...     ...    ...   
746   0.050   0.00034     1.0   0.2517    0.0000     0.4     0.0    2.0   
747   0.062   0.00030     1.0   0.3115    0.0000     0.4     0.0    2.0   
748   0.000   0.00000     1.0   0.0000    0.0000     0.4     0.0    2.0   
749   0.168   0.00000     1.0   0.8400    0.0000     0.4     0.0    2.0   
750   0.436   0.00000     1.0   1.0900    0.0000     0.4     0.0    2.2   
751   0.516   0.00000     1.0   1.2900    0.0000     0.4     0.0    2.2   
752   0.102   0.07400     1.0   0.8800    0.0000     0.4     0.0    2.0   
753   0.018   0.00000     1.0   0.0900    0.0000     0.4     0.0    2.0   
754   0.078   0.18200     1.0   1.3000    0.0000     0.4     0.0    2.0   
755   0.428   0.00000     1.0   1.0700    0.0000     0.4     0.0    2.2   
756   0.000   0.00000     1.0   0.0000    0.0000     0.4     0.0    2.0   
757   0.100   1.78200     1.0   3.4700    0.0360     0.4     0.0    3.2   
758   0.098   0.11000     1.0   1.0400    0.0000     0.4     0.0    2.0   
759   0.168   0.13000     1.0   1.4900    0.0000     0.4     0.0    2.0   
760   0.180   0.44400     1.0   2.0100    0.0000     0.4     0.0    2.6   
761   0.000   0.00000     1.0   0.0000    0.0000     0.4     0.0    2.0   
762   0.118   0.00000     1.0   0.5900    0.0000     0.4     0.0    2.0   
763   0.004   0.00000     1.0   0.0200    0.0000     0.4     0.0    2.0   
764   0.592   2.68800     1.0   5.9600    0.0000     0.4     0.0    3.4   
765   0.000   1.98000     1.0   3.3000    0.0000     0.4     0.0    3.2   
766   0.160   0.11400     1.0   1.3700    0.0000     0.4     0.0    2.0   
767   0.072   0.10800     1.0 